# k8s/global-node/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenzro-global-node
  namespace: tenzro-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenzro-global-node
  template:
    metadata:
      labels:
        app: tenzro-global-node
    spec:
      containers:
        - name: global-node
          image: tenzro/global-node:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_TYPE
              value: "global_node"
            - name: NODE_TIER
              value: "training"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10